package br.com.gda.dao.common;

public final class DaoDbField {
	public static final String COL_BEGIN_TIME = "begin_time";
	public static final String COL_COD_AUTH_GROUP = "cod_auth_group";
	public static final String COL_COD_COMPANY = "cod_company";
	public static final String COL_COD_CURR = "cod_curr";
	public static final String COL_COD_CUSTOMER = "cod_customer";
	public static final String COL_COD_CUSTOMER_SNAPSHOT = "cod_customer_snapshot";	
	public static final String COL_COD_EMPLOYEE = "cod_employee";
	public static final String COL_COD_EMPLOYEE_SNAPSHOT = "cod_employee_snapshot";	
	public static final String COL_COD_ENTITY_CATEG = "cod_entity_categ";
	public static final String COL_COD_LANGUAGE = "language";
	public static final String COL_COD_MATERIAL = "cod_material";	
	public static final String COL_COD_MATERIAL_SNAPSHOT = "cod_material_snapshot";
	public static final String COL_COD_ORDER = "cod_order";
	public static final String COL_COD_OWNER = "cod_owner";
	public static final String COL_COD_PERSON = "cod_person";
	public static final String COL_COD_PERSON_SNAPSHOT = "cod_person_snapshot";
	public static final String COL_COD_SCHEDULE = "cod_schedule";	
	public static final String COL_COD_SNAPSHOT = "cod_snapshot";
	public static final String COL_COD_STORE = "cod_store";
	public static final String COL_COD_STORE_SNAPSHOT = "cod_store_snapshot";	
	public static final String COL_COD_TIME_ZONE = "cod_timezone";
	public static final String COL_COD_USER = "cod_user";
	public static final String COL_COD_USER_CATEG = "cod_user_categ";
	public static final String COL_COD_USER_SNAPSHOT = "cod_user_snapshot";
	public static final String COL_COD_WEEKDAY = "weekday";	
	public static final String COL_COUNTRY_LEGAL = "country_legal";
	public static final String COL_CNPJ = "cnpj";
	public static final String COL_DATE = "date";
	public static final String COL_DAY = "day";
	public static final String COL_EMAIL = "email";
	public static final String COL_END_TIME = "end_time";
	public static final String COL_INSC_MUNICIPAL = "inscricao_municipal";
	public static final String COL_INSC_ESTATUAL = "inscricao_estadual";
	public static final String COL_LAST_CHANGED = "last_changed";
	public static final String COL_LAST_CHANGED_BY = "last_changed_by";
	public static final String COL_MONTH = "month";
	public static final String COL_NAME = "name";
	public static final String COL_QUARTER = "quarter";
	public static final String COL_RAZAO_SOCIAL = "razao_social";
	public static final String COL_RECORD_MODE = "record_mode";	
	public static final String COL_USERNAME = "username";
	public static final String COL_WEEK_MONTH = "week_month";
	public static final String COL_WEEK_YEAR = "week_year";
	public static final String COL_YEAR = "year";
}
