package br.com.mind5.dao.common;

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;

import br.com.mind5.authorization.scheduleAuthorization.dao.DaoSchedauthDbTableColumn;
import br.com.mind5.authorization.storeAuthorization.dao.DaoStorauthDbTableColumn;
import br.com.mind5.business.address.dao.AddressDaoDbTableColumn;
import br.com.mind5.business.addressDefault.dao.AddaultDaoDbTableColumn;
import br.com.mind5.business.addressSearch.dao.AddarchDaoDbTableColumn;
import br.com.mind5.business.addressSnapshot.dao.AddresnapDaoDbTableColumn;
import br.com.mind5.business.addressSnapshotSearch.dao.AddresnaparchDaoDbTableColumn;
import br.com.mind5.business.calendarDate.dao.CalateDaoDbTableColumn;
import br.com.mind5.business.calendarDateSearch.dao.CalatarchDaoDbTableColumn;
import br.com.mind5.business.calendarMonth.dao.CalonthDaoDbTableColumn;
import br.com.mind5.business.calendarMonthSearch.dao.CalontharchDaoDbTableColumn;
import br.com.mind5.business.calendarMoon.dao.MooncalDaoDbTableColumn;
import br.com.mind5.business.calendarWeekYear.dao.CaleekyDaoDbTableColumn;
import br.com.mind5.business.cart.dao.CartDaoDbTableColumn;
import br.com.mind5.business.cartItem.dao.CartemDaoDbTableColumn;
import br.com.mind5.business.cartItemSearch.dao.CartemarchDaoDbTableColumn;
import br.com.mind5.business.cartReserve.dao.CarterveDaoDbTableColumn;
import br.com.mind5.business.company.dao.CompDaoDbTableColumn;
import br.com.mind5.business.companyConflict.dao.CompcoDaoDbTableColumn;
import br.com.mind5.business.companyList.dao.ComplisDaoDbTableColumn;
import br.com.mind5.business.companySearch.dao.DaoComparchDbTableColumn;
import br.com.mind5.business.companySnapshot.dao.DaoCompnapDbTableColumn;
import br.com.mind5.business.customer.dao.CusDaoDbTableColumn;
import br.com.mind5.business.customerList.dao.CuslisDaoDbTableColumn;
import br.com.mind5.business.customerSearch.dao.CusarchDaoDbTableColumn;
import br.com.mind5.business.customerSnapshot.dao.DaoCusnapDbTableColumn;
import br.com.mind5.business.employee.dao.EmpDaoDbTableColumn;
import br.com.mind5.business.employeeLeaveDate.dao.DaoEmplateDbTableColumn;
import br.com.mind5.business.employeeLeaveDateRange.dao.DaoEmplargDbTableColumn;
import br.com.mind5.business.employeeLeaveDateSearch.dao.DaoEmplarchDbTableColumn;
import br.com.mind5.business.employeeList.dao.EmplisDaoDbTableColumn;
import br.com.mind5.business.employeeMaterial.dao.DaoEmpmatDbTableColumn;
import br.com.mind5.business.employeeMaterialSearch.dao.DaoEmpmarchDbTableColumn;
import br.com.mind5.business.employeePosition.dao.DaoEmposDbTableColumn;
import br.com.mind5.business.employeePositionSearch.dao.DaoEmposarchDbTableColumn;
import br.com.mind5.business.employeeSearch.dao.DaoEmparchDbTableColumn;
import br.com.mind5.business.employeeSnapshot.dao.EmpnapDaoDbTableColumn;
import br.com.mind5.business.employeeWorkTime.dao.EmpwotmDaoDbTableColumn;
import br.com.mind5.business.employeeWorkTimeConflict.dao.EmpwocoDaoDbTableColumn;
import br.com.mind5.business.employeeWorkTimeOutlier.dao.EmpwoutDaoDbTableColumn;
import br.com.mind5.business.employeeWorkTimeRange.dao.EmpworgDaoDbTableColumn;
import br.com.mind5.business.employeeWorkTimeSearch.dao.EmpwotarchDaoDbTableColumn;
import br.com.mind5.business.employeeWorkTimeSnapshot.dao.EmpwotmapDaoDbTableColumn;
import br.com.mind5.business.feeDefault.dao.FeedefDaoDbTableColumn;
import br.com.mind5.business.feeOwner.dao.FeewnerDaoDbTableColumn;
import br.com.mind5.business.material.dao.MatDaoDbTableColumn;
import br.com.mind5.business.materialList.dao.MatlisDaoDbTableColumn;
import br.com.mind5.business.materialMovement.dao.DaoMatmovDbTableColumn;
import br.com.mind5.business.materialMovementSearch.dao.DaoMatmarchDbTableColumn;
import br.com.mind5.business.materialSearch.dao.DaoMatarchDbTableColumn;
import br.com.mind5.business.materialSnapshot.dao.DaoMatsnapDbTableColumn;
import br.com.mind5.business.materialStock.dao.DaoMatockDbTableColumn;
import br.com.mind5.business.materialStockSearch.dao.DaoMatocarchDbTableColumn;
import br.com.mind5.business.materialStore.dao.DaoMatoreDbTableColumn;
import br.com.mind5.business.materialStoreSearch.dao.DaoMatorarchDbTableColumn;
import br.com.mind5.business.materialStoreSnapshot.dao.DaoMatorapDbTableColumn;
import br.com.mind5.business.materialText.dao.DaoMatextDbTableColumn;
import br.com.mind5.business.materialTextDefault.dao.DaoMatextaultDbTableColumn;
import br.com.mind5.business.materialTextSearch.dao.DaoMatextarchDbTableColumn;
import br.com.mind5.business.materialTextSnapshot.dao.DaoMatextsnapDbTableColumn;
import br.com.mind5.business.notes.dao.DaoNotesDbTableColumn;
import br.com.mind5.business.order.dao.OrderDaoDbTableColumn;
import br.com.mind5.business.orderItem.dao.OrderemDaoDbTableColumn;
import br.com.mind5.business.orderItemList.dao.OrdemistDaoDbTableColumn;
import br.com.mind5.business.orderItemSearch.dao.DaoOrdemarchDbTableColumn;
import br.com.mind5.business.orderItemSnapshot.dao.OrdemrapDaoDbTableColumn;
import br.com.mind5.business.orderList.dao.OrdistDaoDbTableColumn;
import br.com.mind5.business.orderReserve.dao.DaoOrderveDbTableColumn;
import br.com.mind5.business.orderSearch.dao.DaoOrdarchDbTableColumn;
import br.com.mind5.business.orderSnapshot.dao.DaoOrdnapDbTableColumn;
import br.com.mind5.business.owner.dao.DaoOwnerDbTableColumn;
import br.com.mind5.business.ownerList.dao.OwnelisDaoDbTableColumn;
import br.com.mind5.business.ownerSearch.dao.DaoOwnarchDbTableColumn;
import br.com.mind5.business.ownerSnapshot.dao.DaoOwnerapDbTableColumn;
import br.com.mind5.business.person.dao.PersonDaoDbTableColumn;
import br.com.mind5.business.personBio.dao.DaoPerbioDbTableColumn;
import br.com.mind5.business.personBioSearch.dao.DaoPerbiorchDbTableColumn;
import br.com.mind5.business.personBioSnapshot.dao.DaoPerbionapDbTableColumn;
import br.com.mind5.business.personList.dao.PersolisDaoDbTableColumn;
import br.com.mind5.business.personSearch.dao.DaoPerarchDbTableColumn;
import br.com.mind5.business.personSnapshot.dao.DaoPersonapDbTableColumn;
import br.com.mind5.business.pet.dao.PetDaoDbTableColumn;
import br.com.mind5.business.petDefault.dao.PetaultDaoDbTableColumn;
import br.com.mind5.business.petSearch.dao.PetarchDaoDbTableColumn;
import br.com.mind5.business.petSnapshot.dao.PetsnapDaoDbTableColumn;
import br.com.mind5.business.phone.dao.PhoneDaoDbTableColumn;
import br.com.mind5.business.phoneDefault.dao.DaoPhonaultDbTableColumn;
import br.com.mind5.business.phoneSearch.dao.DaoPhonarchDbTableColumn;
import br.com.mind5.business.phoneSnapshot.dao.DaoPhonapDbTableColumn;
import br.com.mind5.business.phoneSnapshotSearch.dao.DaoPhonaparchDbTableColumn;
import br.com.mind5.business.planingData.dao.PlanataDaoDbTableColumn;
import br.com.mind5.business.refundPolicyOwner.dao.DaoRefupownDbTableColumn;
import br.com.mind5.business.refundPolicyStore.dao.DaoRefuporeDbTableColumn;
import br.com.mind5.business.refundPolicyStoreSearch.dao.DaoRefuporarchDbTableColumn;
import br.com.mind5.business.scheduleDayData.dao.SchedaytaDaoDbTableColumn;
import br.com.mind5.business.scheduleLine.dao.SchedineDaoDbTableColumn;
import br.com.mind5.business.scheduleLineSnapshot.dao.DaoSchedinapDbTableColumn;
import br.com.mind5.business.scheduleList.dao.SchedistDaoDbTableColumn;
import br.com.mind5.business.scheduleMonthData.dao.SchedonthatDaoDbTableColumn;
import br.com.mind5.business.scheduleMoviment.dao.DaoSchedovmDbTableColumn;
import br.com.mind5.business.scheduleRange.dao.DaoSchedageDbTableColumn;
import br.com.mind5.business.scheduleReserve.dao.SchederveDaoDbTableColumn;
import br.com.mind5.business.scheduleSearch.dao.DaoSchedarchDbTableColumn;
import br.com.mind5.business.scheduleWeekData.dao.SchedeekdatDaoDbTableColumn;
import br.com.mind5.business.scheduleYearData.dao.SchedyeratDaoDbTableColumn;
import br.com.mind5.business.store.dao.StoreDaoDbTableColumn;
import br.com.mind5.business.storeFavorite.dao.StoriteDaoDbTableColumn;
import br.com.mind5.business.storeFavoriteSearch.dao.DaoStoritarchDbTableColumn;
import br.com.mind5.business.storeLeaveDate.dao.DaoStolateDbTableColumn;
import br.com.mind5.business.storeLeaveDateRange.dao.DaoStolargDbTableColumn;
import br.com.mind5.business.storeLeaveDateSearch.dao.DaoStolarchDbTableColumn;
import br.com.mind5.business.storeList.dao.StolisDaoDbTableColumn;
import br.com.mind5.business.storeNearby.dao.StorbyDaoDbTableColumn;
import br.com.mind5.business.storeProspect.dao.StoprosDaoDbTableColumn;
import br.com.mind5.business.storeProspectSearch.dao.DaoStoprarchDbTableColumn;
import br.com.mind5.business.storeSearch.dao.DaoSotarchDbTableColumn;
import br.com.mind5.business.storeSnapshot.dao.StorapDaoDbTableColumn;
import br.com.mind5.business.storeText.dao.StorextDaoDbTableColumn;
import br.com.mind5.business.storeTextDefault.dao.DaoStorextaultDbTableColumn;
import br.com.mind5.business.storeTextSearch.dao.DaoStorextarchDbTableColumn;
import br.com.mind5.business.storeTextSnapshot.dao.DaoStorextsnapDbTableColumn;
import br.com.mind5.business.storeWorkTime.dao.StowotmDaoDbTableColumn;
import br.com.mind5.business.storeWorkTimeRange.dao.StoworgDaoDbTableColumn;
import br.com.mind5.business.storeWorkTimeSearch.dao.StowotarchDaoDbTableColumn;
import br.com.mind5.business.storeWorkTimeSnapshot.dao.StowotmapDaoDbTableColumn;
import br.com.mind5.common.SystemLog;
import br.com.mind5.common.SystemMessage;
import br.com.mind5.config.sysDistrictSearch.dao.DaoSysdistrDbTableColumn;
import br.com.mind5.config.sysOwnerConfig.dao.DaoSysonfigDbTableColumn;
import br.com.mind5.config.sysOwnerSignup.dao.DaoSysonupDbTableColumn;
import br.com.mind5.config.sysStoreBusinessContent.dao.DaoSytorbcDbTableColumn;
import br.com.mind5.config.sysStorePartitioning.dao.DaoSytotinDbTableColumn;
import br.com.mind5.config.sysStoreSignup.dao.DaoSysotupDbTableColumn;
import br.com.mind5.dao.DaoColumn;
import br.com.mind5.dao.DaoDbTableColumn;
import br.com.mind5.discount.discountCouponItem.dao.DaoDisoupemDbTableColumn;
import br.com.mind5.discount.discountStore.dao.DaoDisoreDbTableColumn;
import br.com.mind5.discount.discountStoreSearch.dao.DaoDisorarchDbTableColumn;
import br.com.mind5.discount.discountStoreSnapshot.dao.DaoDisorapDbTableColumn;
import br.com.mind5.file.fileImage.dao.DaoFimgDbTableColumn;
import br.com.mind5.file.fileImageList.dao.DaoFimistDbTableColumn;
import br.com.mind5.file.fileImageSearch.dao.DaoFimarchDbTableColumn;
import br.com.mind5.file.fileImageSnapshot.dao.DaoFimgnapDbTableColumn;
import br.com.mind5.file.filePath.dao.DaoFathDbTableColumn;
import br.com.mind5.file.sysFileImage.dao.DaoFimgysDbTableColumn;
import br.com.mind5.file.sysFileImageSearch.dao.DaoFimgysarchDbTableColumn;
import br.com.mind5.file.sysFileImageSnapshot.dao.DaoFimgysapDbTableColumn;
import br.com.mind5.form.formAddress.dao.DaoFormessDbTableColumn;
import br.com.mind5.form.formPhone.dao.DaoFormoneDbTableColumn;
import br.com.mind5.masterData.areaPhone.dao.DaoAreaneDbTableColumn;
import br.com.mind5.masterData.areaPhoneSearch.dao.DaoAreanarchDbTableColumn;
import br.com.mind5.masterData.authorizationGroup.dao.DaoAuthgroupDbTableColumn;
import br.com.mind5.masterData.authorizationGroupRole.dao.DaoAuthgroleDbTableColumn;
import br.com.mind5.masterData.businessArea.dao.DaoBusareaDbTableColumn;
import br.com.mind5.masterData.businessAreaSearch.dao.DaoBusarearchDbTableColumn;
import br.com.mind5.masterData.cartItemCategory.dao.DaoCaritegDbTableColumn;
import br.com.mind5.masterData.cartItemCategorySearch.dao.DaoCaritegarchDbTableColumn;
import br.com.mind5.masterData.country.dao.DaoCountryDbTableColumn;
import br.com.mind5.masterData.countryLegal.dao.DaoCountralDbTableColumn;
import br.com.mind5.masterData.countryLegalSearch.dao.DaoCountrarchDbTableColumn;
import br.com.mind5.masterData.countryPhone.dao.DaoCountroneDbTableColumn;
import br.com.mind5.masterData.countryPhoneSearch.dao.DaoCountronarchDbTableColumn;
import br.com.mind5.masterData.countrySearch.dao.DaoCountarchDbTableColumn;
import br.com.mind5.masterData.currency.dao.DaoCurrencyDbTableColumn;
import br.com.mind5.masterData.currencySearch.dao.DaoCurrarshDbTableColumn;
import br.com.mind5.masterData.dayParting.dao.DaoDaypartDbTableColumn;
import br.com.mind5.masterData.dayPartingSearch.dao.DaoDayparchDbTableColumn;
import br.com.mind5.masterData.discountStrategy.dao.DaoDisegyDbTableColumn;
import br.com.mind5.masterData.entityCategory.dao.DaoEntitegDbTableColumn;
import br.com.mind5.masterData.feeCategory.dao.DaoFeecatDbTableColumn;
import br.com.mind5.masterData.feeCategorySearch.dao.DaoFeecatarchDbTableColumn;
import br.com.mind5.masterData.fileDocType.dao.DaoFidoceDbTableColumn;
import br.com.mind5.masterData.fileDocTypeSearch.dao.DaoFidocarchDbTableColumn;
import br.com.mind5.masterData.gender.dao.DaoGenderDbTableColumn;
import br.com.mind5.masterData.genderSearch.dao.DaoGendarchDbTableColumn;
import br.com.mind5.masterData.language.dao.DaoLanguDbTableColumn;
import br.com.mind5.masterData.languageSearch.dao.DaoLangarchDbTableColumn;
import br.com.mind5.masterData.materialCategory.dao.DaoMategDbTableColumn;
import br.com.mind5.masterData.materialCategorySearch.dao.DaoMategarchDbTableColumn;
import br.com.mind5.masterData.materialGroup.dao.DaoMatoupDbTableColumn;
import br.com.mind5.masterData.materialGroupSearch.dao.DaoMatouparchDbTableColumn;
import br.com.mind5.masterData.materialSubgroup.dao.DaoMatubupDbTableColumn;
import br.com.mind5.masterData.materialSubgroupSearch.dao.DaoMatubuparchDbTableColumn;
import br.com.mind5.masterData.materialType.dao.DaoMatypeDbTableColumn;
import br.com.mind5.masterData.materialTypeSearch.dao.DaoMatyparchDbTableColumn;
import br.com.mind5.masterData.materialUnit.dao.DaoMatunitDbTableColumn;
import br.com.mind5.masterData.materialUnitSearch.dao.DaoMatunitarchDbTableColumn;
import br.com.mind5.masterData.month.dao.DaoMonthDbTableColumn;
import br.com.mind5.masterData.monthSearch.dao.DaoMontharchDbTableColumn;
import br.com.mind5.masterData.moonPhase.dao.DaoMoonaseDbTableColumn;
import br.com.mind5.masterData.moonPhaseSearch.dao.DaoMoonasarchDbTableColumn;
import br.com.mind5.masterData.movimentType.dao.DaoMamovypeDbTableColumn;
import br.com.mind5.masterData.orderStatus.dao.DaoOrderatusDbTableColumn;
import br.com.mind5.masterData.orderStatusSearch.dao.DaoOrderatarchDbTableColumn;
import br.com.mind5.masterData.paymentPartner.dao.DaoPayparDbTableColumn;
import br.com.mind5.masterData.paymentStatus.dao.DaoPaymenusDbTableColumn;
import br.com.mind5.masterData.paymentStatusSearch.dao.DaoPaymenusarchDbTableColumn;
import br.com.mind5.masterData.petType.dao.DaoPetypeDbTableColumn;
import br.com.mind5.masterData.petTypeSearch.dao.DaoPetyparchDbTableColumn;
import br.com.mind5.masterData.petWeight.dao.DaoPeteightDbTableColumn;
import br.com.mind5.masterData.petWeightSearch.dao.DaoPeteightarchDbTableColumn;
import br.com.mind5.masterData.position.dao.DaoPositionDbTableColumn;
import br.com.mind5.masterData.prospectStatus.dao.DaoProstusDbTableColumn;
import br.com.mind5.masterData.prospectStatusSearch.dao.DaoProstarchDbTableColumn;
import br.com.mind5.masterData.refundPolicy.dao.DaoRefupoDbTableColumn;
import br.com.mind5.masterData.refundPolicyGroup.dao.DaoRefugroupDbTableColumn;
import br.com.mind5.masterData.refundPolicyGroupItem.dao.DaoRefugritemDbTableColumn;
import br.com.mind5.masterData.refundPolicyGroupItemSearch.dao.DaoRefugritarchDbTableColumn;
import br.com.mind5.masterData.refundPolicyGroupSearch.dao.DaoRefugrarchDbTableColumn;
import br.com.mind5.masterData.scheduleStatus.dao.DaoSchedatusDbTableColumn;
import br.com.mind5.masterData.state.dao.DaoStateDbTableColumn;
import br.com.mind5.masterData.stateSearch.dao.DaoStatarchDbTableColumn;
import br.com.mind5.masterData.sysEnvironment.dao.DaoSysenvDbTableColumn;
import br.com.mind5.masterData.timezone.dao.DaoTimezoneDbTableColumn;
import br.com.mind5.masterData.timezoneSearch.dao.DaoTimezonarchDbTableColumn;
import br.com.mind5.masterData.userCategory.dao.DaoUseregDbTableColumn;
import br.com.mind5.masterData.weekday.dao.DaoWeekdayDbTableColumn;
import br.com.mind5.masterData.weekdaySearch.dao.DaoWeekdarchDbTableColumn;
import br.com.mind5.message.email.dao.DaoEmailDbTableColumn;
import br.com.mind5.message.emailBody.dao.DaoEmabodyDbTableColumn;
import br.com.mind5.message.sysMessage.dao.DaoSymsgDbTableColumn;
import br.com.mind5.payment.countryPartner.dao.DaoCounparDbTableColumn;
import br.com.mind5.payment.countryPartnerSearch.dao.DaoCounparchDbTableColumn;
import br.com.mind5.payment.creditCard.dao.DaoCrecardDbTableColumn;
import br.com.mind5.payment.creditCardSearch.dao.DaoCrecarchDbTableColumn;
import br.com.mind5.payment.customerPartner.dao.DaoCusparDbTableColumn;
import br.com.mind5.payment.customerPartnerSearch.dao.DaoCusparchDbTableColumn;
import br.com.mind5.payment.ownerPartner.dao.DaoOwnparDbTableColumn;
import br.com.mind5.payment.payOrder.dao.DaoPayordDbTableColumn;
import br.com.mind5.payment.payOrderItem.dao.DaoPayordemDbTableColumn;
import br.com.mind5.payment.payOrderItemList.dao.DaoPayordemistDbTableColumn;
import br.com.mind5.payment.payOrderItemSearch.dao.DaoPayormarchDbTableColumn;
import br.com.mind5.payment.payOrderList.dao.DaoPayordistDbTableColumn;
import br.com.mind5.payment.payOrderSearch.dao.DaoPayordarchDbTableColumn;
import br.com.mind5.payment.setupPartner.dao.DaoSetuparDbTableColumn;
import br.com.mind5.payment.storePartner.dao.StoparDaoDbTableColumn;
import br.com.mind5.payment.storePartnerList.dao.StoplisDaoDbTableColumn;
import br.com.mind5.payment.storePartnerSearch.dao.StoparchDaoDbTableColumn;
import br.com.mind5.payment.storePartnerSnapshot.dao.DaoStoparnapDbTableColumn;
import br.com.mind5.payment.systemPartner.dao.DaoSysparDbTableColumn;
import br.com.mind5.payment.systemPartnerSearch.dao.DaoSysparchDbTableColumn;
import br.com.mind5.paymentPartner.partnerMoip.permissionMoip.dao.DaoPeresmoipDbTableColumn;
import br.com.mind5.security.otpProspectStore.dao.DaoOtporeDbTableColumn;
import br.com.mind5.security.otpUserPassword.dao.DaoOtperasDbTableColumn;
import br.com.mind5.security.user.dao.DaoUserDbTableColumn;
import br.com.mind5.security.userList.dao.DaoUselisDbTableColumn;
import br.com.mind5.security.userPassword.dao.DaoUpswdDbTableColumn;
import br.com.mind5.security.userPasswordSearch.dao.DaoUpswdarchDbTableColumn;
import br.com.mind5.security.userSearch.dao.DaoUserarchDbTableColumn;
import br.com.mind5.security.userSnapshot.dao.DaoUserapDbTableColumn;
import br.com.mind5.security.username.dao.DaoUsernameDbTableColumn;
import br.com.mind5.stats.statsCustomerProfile.customerProfileMonthAggr.dao.CutefilonagrDaoDbTableColumn;
import br.com.mind5.stats.statsCustomerProfile.customerProfileMonthLive.dao.CutefiloniveDaoDbTableColumn;
import br.com.mind5.stats.statsCustomerSchedule.customerScheduleMonthAggr.dao.CustamonagrDaoDbTableColumn;
import br.com.mind5.stats.statsCustomerSchedule.customerScheduleMonthLive.dao.CustamoniveDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerOrder.ownerOrderMonthAggr.dao.SowordagrDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerOrder.ownerOrderMonthLive.dao.SowordiveDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerOrder.ownerOrderMonthSearch.dao.SowordarchDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerSale.ownerSaleAggr.dao.SowalagrDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerSale.ownerSaleLive.dao.SowaliveDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerSchedule.ownerScheduleMonthAggr.dao.SowedulagrDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerSchedule.ownerScheduleMonthLive.dao.SoweduliveDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerSchedule.ownerScheduleMonthSearch.dao.SowedularchDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerStore.ownerStoreMonthAggr.dao.SowotagrDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerStore.ownerStoreMonthLive.dao.SowotiveDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerStore.ownerStoreMonthSearch.dao.SowotarchDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerUser.ownerUserMonthAggr.dao.SowusagrDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerUser.ownerUserMonthLive.dao.SowusiveDaoDbTableColumn;
import br.com.mind5.stats.statsOwnerUser.ownerUserMonthSearch.dao.SowusarchDaoDbTableColumn;
import br.com.mind5.stats.statsStoreOrder.storeOrderDayAggr.dao.DaoStordagrDbTableColumn;
import br.com.mind5.stats.statsStoreOrder.storeOrderDayLive.dao.DaoStordiveDbTableColumn;
import br.com.mind5.stats.statsStoreOrder.storeOrderMonthAggr.dao.DaoStoronagrDbTableColumn;
import br.com.mind5.stats.statsStoreOrder.storeOrderMonthLive.dao.DaoStoroniveDbTableColumn;
import br.com.mind5.stats.statsStoreProfile.storeProfileMonthAggr.dao.StefilonagrDaoDbTableColumn;
import br.com.mind5.stats.statsStoreProfile.storeProfileMonthLive.dao.StefiloniveDaoDbTableColumn;
import br.com.mind5.stats.statsStoreSchedule.storeScheduleDayAggr.dao.SteddagrDaoDbTableColumn;
import br.com.mind5.stats.statsStoreSchedule.storeScheduleDayLive.dao.SteddiveDaoDbTableColumn;
import br.com.mind5.stats.statsStoreSchedule.storeScheduleMonthAggr.dao.StedmonagrDaoDbTableColumn;
import br.com.mind5.stats.statsStoreSchedule.storeScheduleMonthLive.dao.StedmoniveDaoDbTableColumn;
import br.com.mind5.stats.statsUserOrderYear.userOrderYearAggr.dao.DaoStusorygrDbTableColumn;
import br.com.mind5.stats.statsUserOrderYear.userOrderYearAggrSearch.dao.DaoStusorygrarchDbTableColumn;
import br.com.mind5.stats.statsUserOrderYear.userOrderYearLive.dao.DaoStusoryliDbTableColumn;
import br.com.mind5.stats.statsUserOrderYear.userOrderYearLiveSearch.dao.DaoStusorylirchDbTableColumn;
import br.com.mind5.stats.statsUserOrderYear.userOrderYearStgn.dao.DaoStusorygeDbTableColumn;
import br.com.mind5.stats.statsUserOrderYear.userOrderYearStgnSearch.dao.DaoStusorygerchDbTableColumn;
import br.com.mind5.stats.statsUserStore.userStoreAggr.dao.DaoStusoraggDbTableColumn;
import br.com.mind5.stats.statsUserStore.userStoreLive.dao.DaoStusoreveDbTableColumn;
import br.com.mind5.stats.statsUserStore.userStoreStgn.dao.DaoStusorageDbTableColumn;
import br.com.mind5.webhook.moipMultipayment.dao.DaoWokaymoipDbTableColumn;
import br.com.mind5.webhook.moipRefund.dao.DaoWokefumoipDbTableColumn;

public final class DaoDbTableColumnAll {
	private static Hashtable<String, List<DaoColumn>> tableColumns;	
	
	
	static {
		tableColumns = new Hashtable<>();
		
		addTable(new MatDaoDbTableColumn());
		addTable(new DaoMatextDbTableColumn());
		addTable(new DaoEmpmatDbTableColumn());
		addTable(new DaoMatsnapDbTableColumn());
		addTable(new StoreDaoDbTableColumn());
		addTable(new StolisDaoDbTableColumn());
		addTable(new DaoEmposDbTableColumn());
		addTable(new DaoCaritegDbTableColumn());
		addTable(new StowotmDaoDbTableColumn());
		addTable(new DaoStolateDbTableColumn());
		addTable(new EmpwotmDaoDbTableColumn());
		addTable(new DaoEmplateDbTableColumn());
		addTable(new EmpwocoDaoDbTableColumn());
		addTable(new EmpwoutDaoDbTableColumn());
		addTable(new EmpDaoDbTableColumn());
		addTable(new EmpnapDaoDbTableColumn());
		addTable(new EmplisDaoDbTableColumn());
		addTable(new CusDaoDbTableColumn());
		addTable(new DaoOwnerDbTableColumn());
		addTable(new DaoMatoreDbTableColumn());
		addTable(new CartDaoDbTableColumn());
		addTable(new FeewnerDaoDbTableColumn());
		addTable(new FeedefDaoDbTableColumn());
		addTable(new CarterveDaoDbTableColumn());
		addTable(new OrderemDaoDbTableColumn());
		addTable(new OrderDaoDbTableColumn());
		addTable(new AddressDaoDbTableColumn());
		addTable(new AddresnapDaoDbTableColumn());
		addTable(new DaoFormessDbTableColumn());
		addTable(new PhoneDaoDbTableColumn());
		addTable(new DaoPhonapDbTableColumn());
		addTable(new DaoFormoneDbTableColumn());
		addTable(new PersonDaoDbTableColumn());
		addTable(new PersolisDaoDbTableColumn());
		addTable(new DaoPersonapDbTableColumn());
		addTable(new DaoUserDbTableColumn());
		addTable(new DaoUserapDbTableColumn());
		addTable(new StoparDaoDbTableColumn());
		addTable(new DaoCounparDbTableColumn());
		addTable(new CompDaoDbTableColumn());
		addTable(new DaoUpswdDbTableColumn());
		addTable(new DaoUsernameDbTableColumn());
		addTable(new DaoMatmovDbTableColumn());
		addTable(new DaoMatockDbTableColumn());
		addTable(new CusarchDaoDbTableColumn());
		addTable(new PlanataDaoDbTableColumn());
		addTable(new DaoMatextsnapDbTableColumn());
		addTable(new CartemDaoDbTableColumn());
		addTable(new DaoOrderveDbTableColumn());
		addTable(new DaoEmailDbTableColumn());
		addTable(new DaoEmabodyDbTableColumn());
		addTable(new DaoOwnparDbTableColumn());
		addTable(new DaoStoparnapDbTableColumn());
		addTable(new DaoSetuparDbTableColumn());
		addTable(new DaoPayordDbTableColumn());
		addTable(new DaoCusparDbTableColumn());
		addTable(new DaoCrecardDbTableColumn());
		addTable(new DaoSysparchDbTableColumn());
		addTable(new DaoSysparDbTableColumn());
		addTable(new DaoPayordemDbTableColumn());
		addTable(new DaoPeresmoipDbTableColumn());
		addTable(new DaoWokaymoipDbTableColumn());
		addTable(new DaoWokefumoipDbTableColumn());
		addTable(new SchedineDaoDbTableColumn());
		addTable(new StorapDaoDbTableColumn());
		addTable(new DaoCompnapDbTableColumn());
		addTable(new DaoCusnapDbTableColumn());
		addTable(new CuslisDaoDbTableColumn());
		addTable(new DaoUselisDbTableColumn());
		addTable(new DaoSchedinapDbTableColumn());
		addTable(new DaoOrdarchDbTableColumn());
		addTable(new OrdistDaoDbTableColumn());
		addTable(new DaoSchedarchDbTableColumn());
		addTable(new DaoOrdnapDbTableColumn());
		addTable(new OrdemrapDaoDbTableColumn());
		addTable(new DaoPayordarchDbTableColumn());
		addTable(new SchedistDaoDbTableColumn());
		addTable(new DaoSchedovmDbTableColumn());
		addTable(new SchedyeratDaoDbTableColumn());
		addTable(new SchedonthatDaoDbTableColumn());
		addTable(new SchedeekdatDaoDbTableColumn());
		addTable(new DaoFimgDbTableColumn());
		addTable(new DaoFathDbTableColumn());
		addTable(new DaoSymsgDbTableColumn());
		addTable(new DaoOwnerapDbTableColumn());
		addTable(new ComplisDaoDbTableColumn());
		addTable(new AddarchDaoDbTableColumn());
		addTable(new DaoPhonarchDbTableColumn());
		addTable(new DaoSotarchDbTableColumn());
		addTable(new DaoComparchDbTableColumn());
		addTable(new DaoPerarchDbTableColumn());
		addTable(new DaoFimarchDbTableColumn());
		addTable(new DaoFimistDbTableColumn());
		addTable(new DaoStorauthDbTableColumn());
		addTable(new DaoStolarchDbTableColumn());
		addTable(new DaoSchedageDbTableColumn());
		addTable(new StoplisDaoDbTableColumn());
		addTable(new DaoEmposarchDbTableColumn());
		addTable(new StoworgDaoDbTableColumn());
		addTable(new StowotarchDaoDbTableColumn());
		addTable(new EmpwotarchDaoDbTableColumn());
		addTable(new DaoEmplarchDbTableColumn());
		addTable(new DaoEmparchDbTableColumn());
		addTable(new DaoEmpmarchDbTableColumn());
		addTable(new DaoMatextarchDbTableColumn());
		addTable(new DaoMatextaultDbTableColumn());
		addTable(new MatlisDaoDbTableColumn());
		addTable(new DaoMatarchDbTableColumn());
		addTable(new DaoMatorarchDbTableColumn());
		addTable(new DaoMatorapDbTableColumn());
		addTable(new DaoMatocarchDbTableColumn());
		addTable(new DaoMatmarchDbTableColumn());
		addTable(new DaoUserarchDbTableColumn());
		addTable(new StoparchDaoDbTableColumn());
		addTable(new CartemarchDaoDbTableColumn());
		addTable(new EmpworgDaoDbTableColumn());
		addTable(new DaoEmplargDbTableColumn());
		addTable(new DaoStolargDbTableColumn());
		addTable(new DaoOrdemarchDbTableColumn());
		addTable(new CompcoDaoDbTableColumn());
		addTable(new OwnelisDaoDbTableColumn());
		addTable(new DaoCusparchDbTableColumn());
		addTable(new DaoCrecarchDbTableColumn());
		addTable(new DaoCounparchDbTableColumn());
		addTable(new DaoPayormarchDbTableColumn());
		addTable(new DaoPayordistDbTableColumn());
		addTable(new DaoPayordemistDbTableColumn());
		addTable(new DaoMoonasarchDbTableColumn());
		addTable(new DaoMoonaseDbTableColumn());
		addTable(new MooncalDaoDbTableColumn());
		addTable(new CalateDaoDbTableColumn());
		addTable(new DaoStateDbTableColumn());
		addTable(new DaoStatarchDbTableColumn());
		addTable(new DaoLanguDbTableColumn());
		addTable(new DaoLangarchDbTableColumn());
		addTable(new DaoCurrencyDbTableColumn());
		addTable(new DaoCurrarshDbTableColumn());
		addTable(new DaoTimezoneDbTableColumn());
		addTable(new DaoTimezonarchDbTableColumn());
		addTable(new DaoCountroneDbTableColumn());
		addTable(new DaoCountronarchDbTableColumn());
		addTable(new DaoAreaneDbTableColumn());
		addTable(new DaoAreanarchDbTableColumn());
		addTable(new DaoCountryDbTableColumn());
		addTable(new DaoCountarchDbTableColumn());
		addTable(new DaoAuthgroleDbTableColumn());
		addTable(new DaoMategDbTableColumn());
		addTable(new DaoMategarchDbTableColumn());
		addTable(new DaoMatypeDbTableColumn());
		addTable(new DaoMatyparchDbTableColumn());
		addTable(new DaoMatunitDbTableColumn());
		addTable(new DaoMatunitarchDbTableColumn());
		addTable(new DaoBusareaDbTableColumn());
		addTable(new DaoBusarearchDbTableColumn());
		addTable(new DaoMatoupDbTableColumn());
		addTable(new DaoMatouparchDbTableColumn());
		addTable(new DaoGenderDbTableColumn());
		addTable(new DaoGendarchDbTableColumn());
		addTable(new DaoWeekdayDbTableColumn());
		addTable(new DaoWeekdarchDbTableColumn());
		addTable(new DaoDaypartDbTableColumn());
		addTable(new DaoDayparchDbTableColumn());
		addTable(new DaoOrderatusDbTableColumn());
		addTable(new DaoOrderatarchDbTableColumn());
		addTable(new DaoFeecatDbTableColumn());
		addTable(new DaoFeecatarchDbTableColumn());
		addTable(new DaoRefupoDbTableColumn());
		addTable(new DaoRefupownDbTableColumn());
		addTable(new DaoRefuporeDbTableColumn());
		addTable(new DaoRefugroupDbTableColumn());
		addTable(new DaoRefugritemDbTableColumn());
		addTable(new DaoRefugritarchDbTableColumn());
		addTable(new DaoPaymenusDbTableColumn());
		addTable(new DaoPaymenusarchDbTableColumn());
		addTable(new OrdemistDaoDbTableColumn());
		addTable(new SchederveDaoDbTableColumn());
		addTable(new DaoRefugrarchDbTableColumn());
		addTable(new DaoRefuporarchDbTableColumn());
		addTable(new DaoAuthgroupDbTableColumn());
		addTable(new DaoPayparDbTableColumn());
		addTable(new DaoSysenvDbTableColumn());
		addTable(new DaoUseregDbTableColumn());
		addTable(new DaoEntitegDbTableColumn());
		addTable(new DaoPositionDbTableColumn());
		addTable(new DaoMamovypeDbTableColumn());
		addTable(new SchedaytaDaoDbTableColumn());
		addTable(new DaoSchedatusDbTableColumn());
		addTable(new DaoMonthDbTableColumn());
		addTable(new CalatarchDaoDbTableColumn());
		addTable(new DaoMontharchDbTableColumn());
		addTable(new CaleekyDaoDbTableColumn());
		addTable(new DaoSysonupDbTableColumn());
		addTable(new DaoOwnarchDbTableColumn());
		addTable(new DaoFidoceDbTableColumn());
		addTable(new DaoFidocarchDbTableColumn());
		addTable(new DaoOtporeDbTableColumn());
		addTable(new StoprosDaoDbTableColumn());
		addTable(new DaoProstusDbTableColumn());
		addTable(new DaoProstarchDbTableColumn());
		addTable(new DaoStoprarchDbTableColumn());
		addTable(new DaoOtperasDbTableColumn());
		addTable(new DaoSchedauthDbTableColumn());
		addTable(new StorbyDaoDbTableColumn());
		addTable(new DaoNotesDbTableColumn());
		addTable(new DaoSytotinDbTableColumn());
		addTable(new DaoSysonfigDbTableColumn());
		addTable(new DaoUpswdarchDbTableColumn());
		addTable(new DaoMatubupDbTableColumn());
		addTable(new DaoMatubuparchDbTableColumn());
		addTable(new AddaultDaoDbTableColumn());
		addTable(new DaoPhonaultDbTableColumn());
		addTable(new StoriteDaoDbTableColumn());
		addTable(new DaoStoritarchDbTableColumn());
		addTable(new StorextDaoDbTableColumn());
		addTable(new DaoStorextaultDbTableColumn());
		addTable(new DaoStorextarchDbTableColumn());
		addTable(new DaoStorextsnapDbTableColumn());
		addTable(new DaoSysotupDbTableColumn());
		addTable(new DaoSytorbcDbTableColumn());
		addTable(new DaoCountralDbTableColumn());
		addTable(new DaoCountrarchDbTableColumn());
		addTable(new DaoCaritegarchDbTableColumn());
		addTable(new DaoFimgnapDbTableColumn());
		addTable(new AddresnaparchDaoDbTableColumn());
		addTable(new DaoPhonaparchDbTableColumn());
		addTable(new DaoDisegyDbTableColumn());
		addTable(new DaoDisoreDbTableColumn());
		addTable(new DaoDisorarchDbTableColumn());
		addTable(new DaoDisoupemDbTableColumn());
		addTable(new DaoDisorapDbTableColumn());
		addTable(new DaoStusoreveDbTableColumn());
		addTable(new DaoStusorageDbTableColumn());
		addTable(new DaoStusoraggDbTableColumn());
		addTable(new DaoSysdistrDbTableColumn());
		addTable(new DaoStusorygeDbTableColumn());
		addTable(new DaoStusoryliDbTableColumn());
		addTable(new DaoStusorygrDbTableColumn());
		addTable(new DaoStusorygerchDbTableColumn());
		addTable(new DaoStusorylirchDbTableColumn());
		addTable(new DaoStusorygrarchDbTableColumn());
		addTable(new DaoFimgysDbTableColumn());
		addTable(new DaoFimgysarchDbTableColumn());
		addTable(new DaoFimgysapDbTableColumn());
		addTable(new DaoPetypeDbTableColumn());
		addTable(new DaoPetyparchDbTableColumn());
		addTable(new DaoPeteightDbTableColumn());
		addTable(new DaoPeteightarchDbTableColumn());
		addTable(new PetDaoDbTableColumn());
		addTable(new PetsnapDaoDbTableColumn());
		addTable(new PetarchDaoDbTableColumn());
		addTable(new DaoPerbioDbTableColumn());
		addTable(new DaoPerbionapDbTableColumn());
		addTable(new DaoPerbiorchDbTableColumn());
		addTable(new PetaultDaoDbTableColumn());
		addTable(new SowotiveDaoDbTableColumn());
		addTable(new CalonthDaoDbTableColumn());
		addTable(new CalontharchDaoDbTableColumn());
		addTable(new SowusiveDaoDbTableColumn());
		addTable(new SowordiveDaoDbTableColumn());
		addTable(new SoweduliveDaoDbTableColumn());
		addTable(new SowaliveDaoDbTableColumn());
		addTable(new SteddiveDaoDbTableColumn());
		addTable(new SteddagrDaoDbTableColumn());
		addTable(new StedmoniveDaoDbTableColumn());
		addTable(new StedmonagrDaoDbTableColumn());
		addTable(new DaoStordiveDbTableColumn());
		addTable(new DaoStordagrDbTableColumn());
		addTable(new DaoStoroniveDbTableColumn());
		addTable(new DaoStoronagrDbTableColumn());
		addTable(new SowordagrDaoDbTableColumn());
		addTable(new SowordarchDaoDbTableColumn());
		addTable(new SowedulagrDaoDbTableColumn());
		addTable(new SowedularchDaoDbTableColumn());
		addTable(new SowalagrDaoDbTableColumn());
		addTable(new SowotagrDaoDbTableColumn());
		addTable(new SowotarchDaoDbTableColumn());
		addTable(new SowusarchDaoDbTableColumn());
		addTable(new SowusagrDaoDbTableColumn());
		addTable(new StefiloniveDaoDbTableColumn());
		addTable(new StefilonagrDaoDbTableColumn());
		addTable(new CustamoniveDaoDbTableColumn());
		addTable(new CustamonagrDaoDbTableColumn());
		addTable(new CutefiloniveDaoDbTableColumn());
		addTable(new CutefilonagrDaoDbTableColumn());
		addTable(new StowotmapDaoDbTableColumn());
		addTable(new EmpwotmapDaoDbTableColumn());
	}
	
	
	
	private static void addTable(DaoDbTableColumn tblCol) {
		List<String> tblNames = tblCol.getTableNamesAsList();
		
		for (String eachTblName : tblNames) {
			List<DaoColumn> columns = tblCol.getTableColumnsAsList(eachTblName);
			tableColumns.put(eachTblName, columns);
		}
	}
	
	
	
	public static List<DaoColumn> getTableColumnsAsList(String tableName) {		
		List<DaoColumn> resultColumns = new ArrayList<>();
		List<DaoColumn> columns = getColumns(tableName);				
		
		for (DaoColumn eachColumn : columns) {
			DaoColumn copyColumn = makeClone(eachColumn);
			resultColumns.add(copyColumn);
		}
		
		return resultColumns;
	}
	
	
	
	private static List<DaoColumn> getColumns(String tableName) {
		List<DaoColumn> columns = tableColumns.get(tableName);
		
		
		if (columns == null) {
			logException(new IllegalArgumentException(tableName + " " + SystemMessage.TABLE_NOT_FOUND));
			throw new IllegalArgumentException(tableName + " " + SystemMessage.TABLE_NOT_FOUND);
		}
		
		
		return columns;
	}
	
	
	
	private static DaoColumn makeClone(DaoColumn column) {
		try {
			return (DaoColumn) column.clone();
			
		} catch (CloneNotSupportedException e) {
			logException(e);
			throw new IllegalStateException(e);
		}
	}
	
	
	/*
	public static void clear() {
		if (tableColumns == null)
			return;
		
		tableColumns.clear();
		tableColumns = null;
	}
	*/
	
	
	private static void logException(Exception e) {
		SystemLog.logError(DaoDbTableColumnAll.class, e);
	}
}
